package model;
// Generated Oct 5, 2016 2:06:21 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ad generated by hbm2java
 */
@Entity
@Table(name="ad"
    ,catalog="nienluan"
)
public class Ad  implements java.io.Serializable {


     private Integer id;
     private String tieude;
     private String tomtat;
     private String noidung;
     private String path;

    public Ad() {
    }
    
    public Ad(Ad ad){
        this.id=ad.getId();
        this.noidung=ad.getNoidung();
        this.path=ad.getPath();
        this.tomtat=ad.getTomtat();
        this.tieude=ad.getTieude();
    }
    public Ad(String tieude, String tomtat, String noidung, String path) {
       this.tieude = tieude;
       this.tomtat = tomtat;
       this.noidung = noidung;
       this.path = path;
    }
    @Id
    @GeneratedValue
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="tieude", nullable=false)
    public String getTieude() {
        return this.tieude;
    }
    
    public void setTieude(String tieude) {
        this.tieude = tieude;
    }

    
    @Column(name="tomtat", nullable=false, length=300)
    public String getTomtat() {
        return this.tomtat;
    }
    
    public void setTomtat(String tomtat) {
        this.tomtat = tomtat;
    }

    
    @Column(name="noidung", nullable=false, length=7000)
    public String getNoidung() {
        return this.noidung;
    }
    
    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }

    
    @Column(name="path", nullable=false, length=200)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


