package model;
// Generated Oct 5, 2016 2:06:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Coment generated by hbm2java
 */
@Entity
@Table(name="coment"
    ,catalog="nienluan"
)
public class Coment  implements java.io.Serializable {


     private Integer id;
     private String inventoryId;
     private String name;
     private String path;
     private String comment;
     private String date;

    public Coment() {
    }

    public Coment(String inventoryId, String name, String path, String comment, String date) {
       this.inventoryId = inventoryId;
       this.name = name;
       this.path = path;
       this.comment = comment;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="inventoryId", nullable=false)
    public String getInventoryId() {
        return this.inventoryId;
    }
    
    public void setInventoryId(String inventoryId) {
        this.inventoryId = inventoryId;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="path", nullable=false)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    
    @Column(name="comment", nullable=false)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="date", nullable=false)
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


