package model;
// Generated Oct 5, 2016 2:06:21 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Kh generated by hbm2java
 */
@Entity
@Table(name="kh"
    ,catalog="nienluan"
)
public class Kh  implements java.io.Serializable {


     private String user;
     private String password;
     private String repassword;
     private String name;
     private String phone;
     private String address;
     private String gioitinh;
     private String path;
     private String note;
     private Set<Purchaseorder> purchaseorders = new HashSet<Purchaseorder>(0);

    public Kh() {
    }
    //Ham xya dung sao chep:
    public Kh(Kh k){
        this.user=k.getUser();
        this.password=k.getPassword();
        this.repassword=k.getRepassword();
        this.name=k.getName();
        this.gioitinh=k.getGioitinh();
        this.phone=k.getPhone();
        this.address=k.getAddress();
        this.path=k.getPath();
        this.note=k.getNote();
    }
    
    public Kh(String user) {
        this.user = user;
        
        
    }
    public Kh(String user, String name) {
        this.user = user;
        this.name = name;
        
    }
    public Kh(String user, String password, String repassword, String name, String gioitinh) {
        this.user = user;
        this.password = password;
        this.repassword = repassword;
        this.name = name;
        this.gioitinh = gioitinh;
    }
    
     public Kh(String user, String password, String repassword, String name, String phone, String address, String gioitinh, String path, String note) {
       this.user = user;
       this.password = password;
       this.repassword = repassword;
       this.name = name;
       this.phone = phone;
       this.address = address;
       this.gioitinh = gioitinh;
       this.path = path;
       this.note = note;
       
    }
     
    public Kh(String user, String password, String repassword, String name, String phone, String address, String gioitinh, String path, String note, Set<Purchaseorder> purchaseorders) {
       this.user = user;
       this.password = password;
       this.repassword = repassword;
       this.name = name;
       this.phone = phone;
       this.address = address;
       this.gioitinh = gioitinh;
       this.path = path;
       this.note = note;
       this.purchaseorders = purchaseorders;
    }
   
     @Id 

    
    @Column(name="user", unique=true, nullable=false, length=200)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    
    @Column(name="password", nullable=false, length=200)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="repassword", nullable=false, length=200)
    public String getRepassword() {
        return this.repassword;
    }
    
    public void setRepassword(String repassword) {
        this.repassword = repassword;
    }

    
    @Column(name="name", nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="phone")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="address", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="gioitinh", nullable=false, length=200)
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }

    
    @Column(name="path")
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    
    @Column(name="note")
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    
    @JsonIgnore
    @OneToMany(fetch=FetchType.LAZY, mappedBy="kh")
    public Set<Purchaseorder> getPurchaseorders() {
        return this.purchaseorders;
    }
    
    public void setPurchaseorders(Set<Purchaseorder> purchaseorders) {
        this.purchaseorders = purchaseorders;
    }




}


