package model;
// Generated Oct 5, 2016 2:06:21 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Purchaseorder generated by hbm2java
 */
@Entity
@Table(name="purchaseorder"
    ,catalog="nienluan"
)
public class Purchaseorder  implements java.io.Serializable {


     private Integer purchaseId;
     private Kh kh;
     private String purchaseName;
     private String purchaseDate;
     private BigDecimal total;
     private int status;
     private int give;
     private Set<Purchaseorderdetail> purchaseorderdetails = new HashSet<Purchaseorderdetail>(0);

    public Purchaseorder() {
    }
    public Purchaseorder(Integer  id) {
        this.purchaseId=id;
    }
    public Purchaseorder(Kh kh, String purchaseName, String purchaseDate, BigDecimal total) {
       
        this.kh = kh;
        this.purchaseName = purchaseName;
        this.purchaseDate = purchaseDate;
        this.total = total;
    }
    public Purchaseorder(Kh kh, String purchaseName, String purchaseDate, BigDecimal total, int status, int give) {
       
        this.kh = kh;
        this.purchaseName = purchaseName;
        this.purchaseDate = purchaseDate;
        this.total = total;
        this.status=status;
        this.give=give;
    }
    public Purchaseorder(Integer purchaseId, Kh kh, String purchaseName, String purchaseDate, BigDecimal total, Set<Purchaseorderdetail> purchaseorderdetails) {
       this.purchaseId = purchaseId;
       this.kh = kh;
       this.purchaseName = purchaseName;
       this.purchaseDate = purchaseDate;
       this.total = total;
       this.purchaseorderdetails = purchaseorderdetails;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="purchaseId", unique=true, nullable=false)
    public Integer getPurchaseId() {
        return this.purchaseId;
    }
    
    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }
    
    @JsonIgnore
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user", nullable=false)
    public Kh getKh() {
        return this.kh;
    }
    
    public void setKh(Kh kh) {
        this.kh = kh;
    }

    
    @Column(name="purchaseName", nullable=false)
    public String getPurchaseName() {
        return this.purchaseName;
    }
    
    public void setPurchaseName(String purchaseName) {
        this.purchaseName = purchaseName;
    }

    
    @Column(name="purchaseDate", nullable=false)
    public String getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(String purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    
    @Column(name="total", nullable=false, precision=25, scale=0)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    
    @JsonIgnore
    @OneToMany(fetch=FetchType.LAZY, mappedBy="purchaseorder")
    public Set<Purchaseorderdetail> getPurchaseorderdetails() {
        return this.purchaseorderdetails;
    }
    
    public void setPurchaseorderdetails(Set<Purchaseorderdetail> purchaseorderdetails) {
        this.purchaseorderdetails = purchaseorderdetails;
    }


    @Column(name="status",nullable = false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status=status;
    }
    
    @Column(name="give",nullable = false)
    public int getGive() {
        return this.give;
    }
    
    public void setGive(int give) {
        this.give=give;
    }

}


