package model;
// Generated Oct 5, 2016 2:06:21 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Purchaseorderdetail generated by hbm2java
 */
@Entity
@Table(name="purchaseorderdetail"
    ,catalog="nienluan"
)
public class Purchaseorderdetail  implements java.io.Serializable {


     private Integer id;
     private Inventory inventory;
     private Purchaseorder purchaseorder;
     private int count;
     private String color;
     private double cost;

    public Purchaseorderdetail() {
    }

    public Purchaseorderdetail(Inventory inventory, Purchaseorder purchaseorder, int count,String color, long cost) {
       this.inventory = inventory;
       this.purchaseorder = purchaseorder;
       this.count = count;
       this.color=color;
       this.cost = cost;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @JsonIgnore
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="InventoryId", nullable=false)
    public Inventory getInventory() {
        return this.inventory;
    }
    
    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }
    
    @JsonIgnore
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="purchaseId", nullable=false)
    public Purchaseorder getPurchaseorder() {
        return this.purchaseorder;
    }
    
    public void setPurchaseorder(Purchaseorder purchaseorder) {
        this.purchaseorder = purchaseorder;
    }

    
    @Column(name="count", nullable=false)
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }

    
    @Column(name="color", nullable=false)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    
    @Column(name="cost", nullable=false, precision=20, scale=0)
    public double getCost() {
        return this.cost;
    }
    
    public void setCost(double cost) {
        this.cost = cost;
    }




}


